### ISSUE TITLE
Appium inspector not launching

### ISSUE THREAD

**Issue by GEguy** [willhaben/willtest#4]
Hello I am new to Appium and App test automation.

I am trying all the steps to automate testing using Appium. I made sure the app path points to the IPA file, and I have connected my device and properly entered the UDID. Then I click on launch and once the "Get 200" comes up, I click the "Inspector" icon and I get the following error 

Could Not Launch Appium Inspector

Could not start a new session

Be sure the Appium server is running with an application opened by using the "App Path" parameter in Appium.app (along with package and activity for Android) or by connecting with selenium client and supplying this in the desired capabilities object.

Why is this happening? This seems to be a fairly common post, but I can't figure out what I'm doing wrong. Some people mention somehting about a selenium client? I'm not sure what that is but I have downloaded the two JAR files:

selenium-server-standalone-3.0.1.jar
java-client-4.1.2.jar

What do I do with those files. Thanks for any help! Below are my setup stats:

MacOS Sierra 10.12.3
Xcode 8.2.1
iOS 10.2 
Appium version 1.5.3

**Comment by Seijan** [comment]
Okay I'll try to answer you as best as I can, but you should maybe state this question in the official appium github: https://github.com/appium/appium

But now to your question: 
You can't start the Appium over the launch button in the application, because it does not support this version of OS and the version of XCode. To start the Appium Inspector with this versions you have to start the Appium server over the console and after the server is up and running you have to start the Appium Inspector in the Application. 
The start command is
`appium --default-capabilities '{"fullReset":true}'`
The default capabilities is not necessary but if you want to have the app you install to your device to restart fresh every start you need it.

I don't know if you really need Selenium for it, normally Appium is standalone which doesn't need a selenium server.

**Comment by liptga** [comment]
Please create a follow up issue at appium project at https://github.com/appium/appium

**Comment by GEguy** [comment]
THanks for your response, I reposted this in the main Appium forum. I tried running this command you mentioned in Terminal

appium --default-capabilities '{"fullReset":true}'

But I got back the following response: 

-bash: appium: command not found
